---
- name: restart clamd
  service: name=clamd state=restarted

- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart postfix
  service: name=postfix state=restarted
